MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 6
DATASETS:
  TRAIN: ("simple_clothes_train", "simple_clothes_val")
  TEST: ("simple_clothes_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (2000, )
  MAX_ITER: 2600
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 1
PATHS_CATALOG: "./datasets/simple_clothes/paths_catalog.py"
